### ISSUE TITLE
[问题与 BUG 反馈] systemui oom再现

### ISSUE THREAD

**Issue by 1889737514** [fankes/MIUINativeNotifyIcon#179]
### 模块版本

2.99

### MIUI 版本

14.0.23.3.27

### MIUI 版本类型

开发版

### Android 版本

13

### Xposed 框架名称与版本号

LSPosed 1.8.6

### 与系统界面(系统 UI)同作用域的 Xposed 模块

米客，MIUI QOL，MIUIGMS

### 详细描述问题发生的具体原因

使用一段时间后状态栏等系统界面卡顿，随后fc。
异常提示出现oom

### 提供模块问题 Log 或必要 Log

<details><summary>异常跟踪log</summary><pre><code>

================================================================
    Generated by AppErrorsTracking
    Project Url: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: Redmi
[Device Model]: 22041211AC
[Display]: TP1A.220624.014
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 23765
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20220714.0
[Version Code]: 202207140
[Error Type]: JVM
[Crash Time]: 2023-04-23T23:52:24.807
[Stack Trace]:
java.lang.OutOfMemoryError: Failed to allocate a 528 byte allocation with 2529936 free bytes and 2470KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.ArrayList.<init>(ArrayList.java:166)
	at com.android.internal.graphics.palette.WSMeansQuantizer.calculateClusterDistances(WSMeansQuantizer.java:183)
	at com.android.internal.graphics.palette.WSMeansQuantizer.quantize(WSMeansQuantizer.java:110)
	at com.android.internal.graphics.palette.CelebiQuantizer.quantize(CelebiQuantizer.java:48)
	at com.android.internal.graphics.palette.Palette$Builder.generate(Palette.java:344)
	at android.app.WallpaperColors.fromBitmap(WallpaperColors.java:217)
	at android.app.WallpaperColors.fromBitmap(WallpaperColors.java:179)
	at com.android.systemui.media.MediaControlPanel.lambda$bindArtworkAndColors$10(MediaControlPanel.java:669)
	at com.android.systemui.media.MediaControlPanel.$r8$lambda$rLyN_Qz8VejKYwC-tpuPmVOmZmw(Unknown Source:0)
	at com.android.systemui.media.MediaControlPanel$$ExternalSyntheticLambda16.run(Unknown Source:16)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

</code></pre></details>

<details><summary>LSPosed log</summary><pre><code>

[ 2023-04-23T14:50:26.329     1000: 11483: 11483 I/LSPosed-Bridge  ] [E]--> Try to hook [class com.android.systemui.statusbar.phone.NotificationIconAreaController][public void com.android.systemui.statusbar.phone.NotificationIconAreaController.updateNotificationIcons(java.util.List)] got an Exception [Default]
[ 2023-04-23T14:50:26.329     1000: 11483: 11483 E/LSPosed-Bridge  ] java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 905336 free bytes and 884KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:0)
	at LSPHooker_.getString(Unknown Source:15)
	at android.graphics.drawable.AdaptiveIconDrawable.<init>(AdaptiveIconDrawable.java:169)
	at android.graphics.drawable.AdaptiveIconDrawable$LayerState.newDrawable(AdaptiveIconDrawable.java:1066)
	at android.graphics.drawable.Drawable$ConstantState.newDrawable(Drawable.java:1547)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:678)
	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:307)
	at android.content.res.Resources.loadDrawable(Resources.java:1026)
	at java.lang.reflect.Method.invoke(Native Method)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:1014)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.getDrawableForDensity(Unknown Source:25)
	at android.content.res.Resources.getDrawable(Resources.java:953)
	at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:403)
	at android.graphics.drawable.Icon.loadDrawable(Icon.java:354)
	at p1.c.i0(P:83)
	at p1.c.v0(P:35)
	at p1.c.w0(P:12)
	at p1.c$g.c(P:95)
	at p1.c$g.a(P:3)
	at f3.a$a$c.b(P:25)
	at h3.b.a(P:7)
	at g3.d$j.afterHookedMethod(P:12)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.updateNotificationIcons(Unknown Source:11)
	at com.android.systemui.statusbar.phone.NotificationPanelViewController.updateNotificationViews(NotificationPanelViewController.java:4119)
	at com.android.systemui.statusbar.phone.MiuiNotificationPanelViewController.updateNotificationViews(MiuiNotificationPanelViewController.kt:1357)
	at com.android.systemui.statusbar.phone.StatusBarNotificationPresenter.updateNotificationViews(StatusBarNotificationPresenter.java:360)
	at com.android.systemui.statusbar.notification.MiuiNotificationEntryManager.updateNotifications(MiuiNotificationEntryManager.kt:277)
	at com.android.systemui.statusbar.notification.NotificationEntryManager.updateNotifications(NotificationEntryManager.java:840)
	at com.android.systemui.statusbar.notification.NotificationEntryManager.updateNotificationInternal(NotificationEntryManager.java:809)
	at com.android.systemui.statusbar.notification.NotificationEntryManager.updateNotification(NotificationEntryManager.java:822)
	at com.android.systemui.statusbar.notification.MiuiNotificationEntryManager.updateNotification(MiuiNotificationEntryManager.kt:182)
	at android.content.res.DrawableCache.getInstance(DrawableCache.java:45)
	at com.android.systemui.statusbar.notification.MiuiNotificationEntryManager$notifListener$1.onNotificationPosted(MiuiNotificationEntryManager.kt:111)
	at com.android.systemui.statusbar.NotificationListener.lambda$onNotificationPosted$1(NotificationListener.java:153)
	at com.android.systemui.statusbar.NotificationListener.$r8$lambda$_Jw8Z61nz-hTIhcIoaONGUYINN0(Unknown Source:0)
	at com.android.systemui.statusbar.NotificationListener$$ExternalSyntheticLambda4.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
修不好，就这样吧

**Comment by fankes** [comment]
已修复 #173

**Comment by Zxilly** [comment]
可以用一个固定大小的lrucache来缓存，这样既能加速又不会oom

**Comment by fankes** [comment]
> 可以用一个固定大小的lrucache来缓存，这样既能加速又不会oom

再说

**Comment by Zxilly** [comment]
那可以写一个带expire的hashmap

**Comment by fankes** [comment]
> 那可以写一个带expire的hashmap，和lru一个思路，避免不再使用的图标占据内存，不管是因为单纯没通知了还是hash寄了

这个项目差不多就这样了，想实现你可以 PR 一个，欢迎 PR
